[render]
out_dir = "./outputs"
scene_id = "wine_bottle"
width = 640
height = 480
zmax_m = 6.0


[rig.color_intr]
focal_length_mm = 35.0
clip_start = 0.01
clip_end = 100.0

[rig.depth_intr]
focal_length_mm = 35.0
clip_start = 0.01
clip_end = 100.0

[rig.T_DC]
p = [-0.1, 0.0, 0.0]
q_wxyz = [1.0, 0.0, 0.0, 0.0]


[obj]
kind = "cad"

[obj.cad]
path = "meshes/wine_bottle/wine_bottle.glb"
scale = [0.05, 0.05, 0.05]
color_rgba = [0.8, 0.8, 0.8, 1.0]

[obj.T_WO]
p = [0.0, 0.0, 0.0]
q_wxyz = [0.717, -0.717, 0.0, 0.0]


[[seq.camera_extrinsics]]
p_WC = [1.5, -2.5, 1.4]
p_W_target = [0.0, 0.0, 0.35]

[[seq.camera_extrinsics]]
p_WC = [1.5, 2.5, 1.4]
p_W_target = [0.0, 0.0, 0.35]


[noise]
enabled = true  # if false, skip entire noise processing

[noise.gaussian]
enabled = true
sigma_m = 0.1

[noise.multiplicative]
enabled = true
sigma_rel = 0.01

[noise.quantization]
enabled = true
step_m = 0.001

[noise.dropout]
enabled = true
p = 0.05
fill = 0.0
