[render]
out_dir = "./outputs"
scene_id = "cube_demo"
width = 640
height = 480
zmax_m = 10.0


[rig.color_intr]
focal_length_mm = 35.0
clip_start = 0.01
clip_end = 100.0

[rig.depth_intr]
focal_length_mm = 35.0
clip_start = 0.01
clip_end = 100.0

[rig.T_DC]
p = [-0.1, 0.0, 0.0]
q_wxyz = [1.0, 0.0, 0.0, 0.0]


[obj]
type = "cube"
size = [1.0, 1.0, 1.0]
color_rgba = [0.8, 0.2, 0.2, 1.0]
[obj.T_WO]
p = [0.0, 0.0, 0.5]          # world position of object origin
q_wxyz = [1.0, 0.0, 0.0, 0.0]


[[seq.camera_extrinsics]]
p_WC = [1.5, -2.5, 1.4]
p_W_target = [0.0, 0.0, 0.5]

[[seq.camera_extrinsics]]
p_WC = [1.5, 2.5, 1.4]
p_W_target = [0.0, 0.0, 0.5]

[[seq.camera_extrinsics]]
p_WC = [-1.5, 2.5, 1.4]
p_W_target = [0.0, 0.0, 0.5]

[[seq.camera_extrinsics]]
p_WC = [-1.5, -2.5, 1.4]
p_W_target = [0.0, 0.0, 0.5]

[noise]
enabled = true  # if false, skip entire noise processing

[noise.gaussian]
enabled = true
sigma_m = 0.003

[noise.multiplicative]
enabled = false
sigma_rel = 0.01

[noise.quantization]
enabled = false
step_m = 0.001

[noise.dropout]
enabled = false
p = 0.02
fill = 0.0
